version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@db:5432/flask_auth_db
      - SECRET_KEY=mysecretkey
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flask_auth_db
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql  # Ensure the path is correct for init.sql
    ports:
      - "5432:5432"